version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

  api:
    build:
      dockerfile: ./docker/debug/Dockerfile
      context: ../
    restart: always
    volumes:
      - ../src:/home/node/app/src
    command: yarn nodemon --watch 'src/**/*.ts' --exec node --inspect=0.0.0.0 -r ts-node/register -L ./src/server.ts
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - db

volumes:
  database:
